<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Recoil.Zbd.Verify</RootNamespace>
    <AssemblyName>Recoil.Zbd.Verify</AssemblyName>
  </PropertyGroup>
  <PropertyGroup><OutputType>Exe</OutputType></PropertyGroup>
  <ItemGroup><ProjectReference Include="../../src/zStudio.Core/zStudio.Core.csproj" /></ItemGroup>
</Project>
